require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'

use_modular_headers!

target 'ParentBridgeNew' do
  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => true
  )

  # Add any other dependencies your app needs
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        
        # Add C++ settings
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_HEADER_ONLY=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_NONTYPE_TEMPLATE_PARAMETERS=0'
        
        # Ensure proper header search paths
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << '${PODS_ROOT}/fmt/include'
        config.build_settings['HEADER_SEARCH_PATHS'] << '${PODS_ROOT}/boost-for-react-native'
        
        # Additional build settings
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DFMT_HEADER_ONLY=1'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      end
    end
  end
end
